# Generated by Django 3.2.25 on 2024-03-19 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(default='Enter comment', max_length=50)),
                ('content', models.TextField(default='Enter comment')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenting', to='entries.entry')),
            ],
        ),
    ]
