# Generated by Django 3.2.25 on 2024-03-15 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0003_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='likes',
            field=models.ManyToManyField(related_name='story_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
