# Generated by Django 4.2.11 on 2024-04-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
