# Generated by Django 3.2.25 on 2024-03-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_entry_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='likes',
        ),
        migrations.AddField(
            model_name='entry',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
