# Generated by Django 4.2.11 on 2024-03-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_remove_entry_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
