# Generated by Django 3.2.25 on 2024-03-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20240317_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='Entry',
        ),
    ]
