# Generated by Django 3.2.25 on 2024-03-18 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0007_rename_post_comment_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
